name: todo_app

services:
    nginx:
       image: nginx:alphine
       countainer_name: todo_app-nginx
       restart: unless-stopped
       ports:
        -8000:80
       volumes:


app:
   build:
       context: ./
       dockerfile: dockerfile
      
       container_name: todo_app_app
       restart: unless-stopped
       working_dir: /var/www/


db:

  image: mysql:5.6
  container_name: todo_app-db
  restart: unless-stopped
  environment: 
  MYSQL_ROOT_PASSWORD=my-secret-pwd
  
  MYSQL_USER=${DB_USERNAME}
  MYSQL_PASSWORD=${DB_PASSWORD}
  MYSQL_DATABASE=${DB_DATABASE}